---
- name: Source vars for specific distribution
  loop_control:
    loop_var: vars_file
  with_first_found:
    - "{{ os_distribution }}.yml"
    - "{{ os_family }}.yml"
  ansible.builtin.include_vars:
    file: "{{ vars_file }}"

- name: Source tasks for specific distribution
  loop_control:
    loop_var: tasks_file
  with_first_found:
    - "{{ os_distribution }}.yml"
    - "{{ os_family }}.yml"
  ansible.builtin.include_tasks:
    file: "{{ tasks_file }}"

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Enable nvidia-persistence service
  when: ansible_facts['services']['nvidia-persistenced.service'] is defined
  ansible.builtin.service:
    name: nvidia-persistenced
    enabled: true
