---
- name: Enable required RedHat repos for RHEL9 x86_64
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  loop:
  - rhel-9-for-x86_64-appstream-rpms
  - rhel-9-for-x86_64-baseos-rpms
  - codeready-builder-for-rhel-9-x86_64-rpms
  community.general.dnf_config_manager:
    name: "{{ item }}"
    state: enabled

- name: Install EPEL
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present
    disable_gpg_check: True

- name: Add the NVIDIA Repo for RHEL9 x86_64
  ansible.builtin.uri:
    url: "https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo"
    dest: /etc/yum.repos.d/cuda-rhel9.repo
    owner: root
    group: root
    mode: "644"
    status_code:
    - 200
    - 304

- name: Install packages for RHEL9 x86_64
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  loop:
  - "kernel-devel-{{ ansible_facts['kernel'] }}"
  - "kernel-headers-{{ ansible_facts['kernel'] }}"
  - gcc
  - kmod-nvidia-open-dkms
  - nvidia-driver-cuda
#  - "@nvidia-driver:open-dkms"
  - cuda-toolkit
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present

- name: Enable persistence service
  ansible.builtin.service:
    name: nvidia-persistenced
    state: started
    enabled: True

- name: Disable the nouveau drivers
  notify:
  - Run dracut
  - Reboot
  ansible.builtin.template:
    src: templates/modprobe.j2  
    dest: /etc/modprobe.d/blacklist-nouveau.conf
    owner: root
    group: root
    mode: "644"
