---
- name: Run dracut
  tags: rhel
  changed_when: true
  ansible.builtin.command:
    cmd: dracut --force

- name: Update initramfs
  tags: ubuntu, debian
  changed_when: true
  ansible.builtin.command:
    cmd: update-initramfs -u

- name: Update apt cache
  tags: ubuntu, debian
  changed_when: true
  ansible.builtin.apt:
    update_cache: true

- name: Reboot
  when: inventory_hostname != "localhost"
  ansible.builtin.reboot:
    msg: "Rebooting to finish Nvidia driver installation"
